### ISSUE TITLE
Centos安装Fibos后无法启动

### ISSUE THREAD

**Issue by danjx** [FIBOSIO/fibos#2]
使用官方教程在centos 7.0环境下安装fibos后，无法启动fibos，提示：
fibos: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
但是我的libcrypto已经默认安装好了啊

**Comment by asdfsi** [comment]
没给源码的话，拿他的bin文件在自己的环境下运行就是碰运气

**Comment by zhongxiangLi** [comment]
试下升级下系统版本

**Comment by luoyhang003** [comment]
fibos暂不支持centos
