### ISSUE TITLE
请求提供arm64版本的安装包

### ISSUE THREAD

**Issue by Witnose** [FIBOSIO/fibos#33]

**Comment by richardo2016** [comment]
> _No description provided._

你好, 因为 eos 代码的关系. fibos 暂时没法支持 arm64

**Comment by Entropier** [comment]
> 

您好，我正在尝试自己手动编译，eos已经在arm64的树莓派上编译成功了，但是eos的测试只通过了一项，请问这是您说的eos代码的问题吗？如果是的我就放弃编译了。
